[package]
name = "lambda-calc"
version = "0.1"
path = "."

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "7c72de2be1a07dcd00d343d720162c105d48107b"}
lean-lib = {git = "https://github.com/unitb/lean-lib", rev = "8ed5d87f256fa929156c7dbed14875e5aecd402f"}
