[package]
name = "lambda-calc"
version = "0.1"
lean_version = "master"
path = "."

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "bf58bf4451f26b88c776586865e6840cd1495f64"}
lean-lib = {git = "https://github.com/unitb/lean-lib", rev = "dbd7075b4d0db7956d91451ff05d891b90caaa10"}
